version: '3.8'
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    networks:
      private_network:
        ipv4_address: 10.2.0.200
    cap_add:
      - NET_ADMIN
    env_file: .env
  wireguard:
    depends_on:
      - unbound
      - pihole
    image: linuxserver/wireguard
    container_name: wireguard
    ports:
      - 5000:5000
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - /services/config/wireguard:/config
    env_file: .env
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /services/data/wireguard-ui:/app/db
      - /services/config/wireguard-ui:/config
    env_file: .env
  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - ${PIHOLE_DNS}
    volumes:
      - /services/config/pihole:/etc/pihole/ #TODO
      - /services/config/dnsmasq.d:/etc/dnsmasq.d/ #TODO
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100
    env_file: ./.env
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    environment:
      DISABLE_IPV6: 'true'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./services/data/nginx-proxy-manager:/data:rw
      - ./services/config/letsencrypt:/etc/letsencrypt:rw
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - /services/config/homepage:/app/config
    depends_on: 
      - cloudflare-ddns
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    # ports:
    #   - 9000:9000
    volumes:
      - /services/data/portainer:/data
    cap_add:
      - NET_ADMIN
    depends_on: 
      - cloudflare-ddns
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # ports:
    #   - 443:443
    volumes:
      - /services/data/nextcloud:/data:rw
      - /services/config/nextcloud:/config:rw #TODO
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${DOMAIN}
    # ports:
    #  - 443:80
    volumes:
      - /services/data/vaultwarden:/data:rw
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    environment:
      API_KEY: your_api_token
      ZONE: tur11ng.my.id
      SUBDOMAIN: vpn
    restart: unless-stopped