services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    environment:
      - UNBOUND_IPV4_ADDRESS=10.2.0.100
    volumes:
      - /services/config/unbound:/opt/unbound/etc/unbound:rw 
    networks:
      homelab:
        ipv4_address: 10.2.0.100
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  wireguard:
    image: linuxserver/wireguard:v1.0.20210914-ls7
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - /services/config/wireguard:/config:rw
    networks:
      homelab:
        ipv4_address: 10.2.0.101
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "51820:51820/udp"

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SESSION_SECRET=VerYSsSs3cr3tLoL
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /services/data/wireguard-ui:/app/db:rw
      - /services/config/wireguard-ui:/config:rw
    depends_on:
      - wireguard
      

  # wireguard-ui:
  #   image: ngoduykhanh/wireguard-ui:latest
  #   container_name: wireguard-ui
  #   environment:
  #     - TZ=Europe/Athens
  #     - WGUI_SESSION_SECRET=VerYSsSs3cr3tLoL
  #     - WGUI_USERNAME=admin
  #     - WGUI_MANAGE_START=true
  #     - WGUI_MANAGE_RESTART=true
  #     - WGUI_SERVER_INTERFACE_ADDRESSES=10.2.0.102
  #     - WGUI_DNS=10.2.0.100
  #     - WGUI_LOG_LEVEL=INFO
  #     - WGUI_SERVER_POST_UP_SCRIPT=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
  #     - WGUI_SERVER_POST_DOWN_SCRIPT=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
  #   cap_add:
  #     - NET_ADMIN
  #   network_mode: service:wireguard
  #   # ports:
  #     # - 51820:51820/udp
  #     # - 8080:5000/tcp
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 50m
  #   volumes:
  #     - /services/data/wireguard-ui:/app/db:rw
  #     - /services/config/wireguard-ui:/config:rw
  #   # networks:
  #   #   homelab:
  #   #     ipv4_address: 10.2.0.101
  #   security_opt:
  #     - no-new-privileges:true
  #   restart: unless-stopped
  #   depends_on:
  #     - wireguard
  #     - cloudflare-ddns

  # wireguard:
  #   image: linuxserver/wireguard
  #   container_name: wireguard
  #   environment:
  #     - TZ=Europe/Athens
  #     - PUID=1000
  #     - PGID=1000
  #     - PEERS=2
  #     - SERVERURL=vpn.tur11ng.my.id
  #     - SERVERPORT=51820
  #     - LOG_CONFS=true
  #     - INTERNAL_SUBNET=10.2.0.0/24
  #     - ALLOWEDIPS=0.0.0.0/0
  #     - PEERDNS=10.2.0.100
  #     - PERSISTENTKEEPALIVE_PEERS=25
  #   ports:
  #     - 51820:51820/udp
  #     - 8080:5000/tcp
  #   cap_add:
  #     - NET_ADMIN
  #     # - SYS_MODULE
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #     - net.ipv4.ip_forward=1
  #   volumes:
  #     - /services/config/wireguard:/config:rw
  #   networks:
  #     homelab:
  #       ipv4_address: 10.2.0.102
  #   security_opt:
  #     - no-new-privileges:true
  #   restart: unless-stopped
  #   depends_on:
  #     - unbound
  #     - pihole
  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - PIHOLE_IPV4_ADDRESS=10.2.0.103
      - WEBPASSWORD=${WEBPASSWORD}
    dns:
      - 10.2.0.100
    volumes:
      - /services/config/pihole:/etc/pihole:rw
      - /services/config/dnsmasq:/etc/dnsmasq.d:rw
    cap_add:
      - NET_ADMIN
    networks:
      homelab:
        ipv4_address: 10.2.0.103
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns
      - unbound

  # openvpn:
  #   image: kylemanna/openvpn
  #   container_name: openvpn
  #   ports:
  #     - "1194:1194/udp"
  #   volumes:
  #    - /services/config/openvpn/:/etc/openvpn
  #   cap_add:
  #     - NET_ADMIN
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #     - net.ipv4.ip_forward=1
  #   networks:
  #     homelab:
  #       ipv4_address: 10.2.0.102
  #   security_opt:
  #     - no-new-privileges:true
  #   restart: unless-stopped
  #   depends_on:
  #     - unbound
  #     - pihole
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   environment:
  #     - PIHOLE_IPV4_ADDRESS=10.2.0.103
  #     - WEBPASSWORD=${WEBPASSWORD}
  #   dns:
  #     - 10.2.0.100
  #   volumes:
  #     - /services/config/pihole:/etc/pihole:rw
  #     - /services/config/dnsmasq:/etc/dnsmasq.d:rw
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     homelab:
  #       ipv4_address: 10.2.0.103
  #   security_opt:
  #     - no-new-privileges:true
  #   restart: unless-stopped
  #   depends_on:
  #     - cloudflare-ddns
  #     - unbound

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    environment:
      - DISABLE_IPV6=true
    # ports:
    #   - '80:80'
    #   - '443:443'
    #   - '81:81'
    volumes:
      - /services/data/nginx-proxy-manager:/data:rw
      - /services/config/letsencrypt:/etc/letsencrypt:rw
    networks:
      homelab:
        ipv4_address: 10.2.0.104
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - /services/config/homepage:/app/config:rw
    networks:
      homelab:
        ipv4_address: 10.2.0.105
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer
  #   # ports:
  #   #   - 9000:9000
  #   volumes:
  #     - /services/data/portainer:/data
  #   networks:
  #     homelab:
  #       ipv4_address: 10.2.0.106
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped
  #   depends_on: 
  #     - cloudflare-ddns

  # nextcloud:
  #   image: lscr.io/linuxserver/nextcloud:latest
  #   container_name: nextcloud
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   # ports:
  #   #   - 443:443
  #   volumes:
  #     - /services/data/nextcloud:/data:rw
  #     - /services/config/nextcloud:/config:rw
  #   networks:
  #     homelab:
  #       ipv4_address: 10.2.0.107
  #   security_opt:
  #     - no-new-privileges
  #   restart: unless-stopped
  #   depends_on: 
  #     - cloudflare-ddns

  # vaultwarden:
  #   image: vaultwarden/server:latest
  #   container_name: vaultwarden
  #   environment:
  #     - ADMIN_TOKEN=${ADMIN_TOKEN}
  #     - WEBSOCKET_ENABLED=true
  #     - SIGNUPS_ALLOWED=false
  #     - DOMAIN=${DOMAIN}
  #   # ports:
  #   #  - 443:80
  #   volumes:
  #     - /services/data/vaultwarden:/data:rw
  #   networks:
  #     homelab:
  #       ipv4_address: 10.2.0.108
  #   restart: unless-stopped
  #   depends_on: 
  #     - cloudflare-ddns

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    networks:
      homelab:
        ipv4_address: 10.2.0.109
    restart: unless-stopped
    volumes:
      - /services/config/cloudflare-ddns/config.json:/config.json:rw

networks:
  homelab:
    ipam:
      config:
        - subnet: 10.2.0.0/24