version: '3.8'
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    environment:
      - UNBOUND_IPV4_ADDRESS: 10.2.0.100
    volumes:
      - ./unbound:/opt/unbound/etc/unbound:rw 
    networks:
      default:
        ipv4_address: 10.2.0.100
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    environment:
      - WGUI_SESSION_SECRET: VerYSsSs3cr3tLoL
      - WGUI_USERNAME: admin
      - WGUI_PASSWORD: ${WGUI_PASSWORD}
      - WGUI_MANAGE_START: true
      - WGUI_MANAGE_RESTART: true
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /services/data/wireguard-ui:/app/db:rw
      - /services/config/wireguard-ui:/config:rw
    security_opt:
      - no-new-privileges
    restart: unless_stopped
    depends_on:
      - wireguard
      - cloudflare-ddns

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    environment:
      - WIREGUARD_PEERS: 1
      - WIREGUARD_PEER_DNS: 10.2.0.102
      - WIREGUARD_SERVER_PORT: 51820
    ports:
      - 5000:5000
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - /services/config/wireguard:/config:rw
    networks:
      default:
        ipv4_address: 10.2.0.102
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    depends_on:
      - unbound
      - pihole

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - PIHOLE_IPV4_ADDRESS: 10.2.0.103
      - WEBPASSWORD: ${WEBPASSWORD}
    hostname: pihole
    dns:
      - 10.2.0.100
    volumes:
      - /services/config/pihole:/etc/pihole:rw
      - /services/config/dnsmasq:/etc/dnsmasq.d:rw
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 10.2.0.103
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns
      - unbound

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    environment:
      - DISABLE_IPV6: 'true'
    # ports:
    #   - '80:80'
    #   - '443:443'
    #   - '81:81'
    volumes:
      - ./services/data/nginx-proxy-manager:/data:rw
      - ./services/config/letsencrypt:/etc/letsencrypt:rw
    networks:
      default:
        ipv4_address: 10.2.0.104
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - /services/config/homepage:/app/config:rw
    networks:
      default:
        ipv4_address: 10.2.0.105
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # ports:
    #   - 9000:9000
    volumes:
      - /services/data/portainer:/data
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # ports:
    #   - 443:443
    volumes:
      - /services/data/nextcloud:/data:rw
      - /services/config/nextcloud:/config:rw
    networks:
      default:
        ipv4_address: 10.2.0.106
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${DOMAIN}
    # ports:
    #  - 443:80
    volumes:
      - /services/data/vaultwarden:/data:rw
    restart: unless-stopped
    depends_on: 
      - cloudflare-ddns

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    networks:
      default:
        ipv4_address: 10.2.0.107
    restart: unless-stopped
    volumes:
      - /services/config/cloudflare-ddns/config.json:/config.json:rw

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
