services:
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    environment:
      - UNBOUND_IPV4_ADDRESS=10.2.0.100
    volumes:
      - /services/config/unbound:/opt/unbound/etc/unbound:rw
    networks:
      homelab:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:v1.0.20210914-ls7
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - /services/config/wireguard:/config:rw
      - /services/config/wireguard-ui/wg0.conf:/config/wg0.conf:rw
    dns:
      - 192.168.1.2
    networks:
      homelab:
        ipv4_address: 192.168.1.3
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    restart: unless-stopped

  wireguard-ui:
    container_name: wireguard-ui
    image: ngoduykhanh/wireguard-ui:latest
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SESSION_SECRET=VerYSsSs3cr3tLoL
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /services/data/wireguard-ui:/app/db:rw
      - /services/config/wireguard-ui:/config:rw
    depends_on:
      - wireguard

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - PIHOLE_IPV4_ADDRESS=10.2.0.103
      - WEBPASSWORD=${WEBPASSWORD}
    dns:
      - 192.168.1.2
    networks:
      homelab:
        ipv4_address: 192.168.1.4
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - cloudflare-ddns
      - unbound

  hello:
    container_name: hello
    image: nginxdemos/hello:latest
    dns:
      - 192.168.1.2
    networks:
      homelab:
        ipv4_address: 192.168.1.5
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - cloudflare-ddns
      - unbound

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    dns:
      - 192.168.1.2
    environment:
      - DISABLE_IPV6=true
    volumes:
      - /services/data/nginx-proxy-manager:/data:rw
      - /services/config/letsencrypt:/etc/letsencrypt:rw
    networks:
      homelab:
        ipv4_address: 192.168.1.6
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    dns:
      - 192.168.1.2
    volumes:
      - /services/config/homepage:/app/config:rw
    networks:
      homelab:
        ipv4_address: 192.168.1.7
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    dns:
      - 192.168.1.2
    volumes:
      - /services/data/portainer:/data
    networks:
      homelab:
        ipv4_address: 192.168.1.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    dns:
      - 192.168.1.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /services/data/nextcloud:/data:rw
      - /services/config/nextcloud:/config:rw
    networks:
      homelab:
        ipv4_address: 192.168.1.9
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    dns:
      - 192.168.1.2
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${DOMAIN}
    volumes:
      - /services/data/vaultwarden:/data:rw
    networks:
      homelab:
        ipv4_address: 192.168.1.10
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: timothyjmiller/cloudflare-ddns:latest
    dns:
      - 192.168.1.2
    security_opt:
      - no-new-privileges:true
    networks:
      homelab:
        ipv4_address: 192.168.1.11
    restart: unless-stopped
    volumes:
      - /services/config/cloudflare-ddns/config.json:/config.json:rw

networks:
  homelab:
    ipam:
      config:
        - subnet: 192.168.1.0/24
