services:
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    environment:
      - UNBOUND_IPV4_ADDRESS=192.168.100.2
    volumes:
      - /services/config/unbound:/opt/unbound/etc/unbound:rw
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.2
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:v1.0.20210914-ls7
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - /services/config/wireguard:/config:rw
      - /services/config/wireguard-ui/wg0.conf:/config/wg0.conf:rw
    dns:
      - 192.168.100.2
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.3
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns
      - unbound

  wireguard-ui:
    container_name: wireguard-ui
    image: ngoduykhanh/wireguard-ui:latest
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - WGUI_USERNAME=${WGUI_USERNAME}
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /services/data/wireguard-ui:/app/db:rw
      - /services/config/wireguard-ui:/config:rw
    depends_on:
      - wireguard
      - cloudflare-ddns
      - unbound

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - DNS1=192.168.100.2
      - DNS2=192.168.100.2
      - PIHOLE_IPV4_ADDRESS=192.168.100.3
      - WEBPASSWORD=${WEBPASSWORD}
    dns:
      - 192.168.100.2
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.4
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  nginx-proxy-manager:
    container_name: nginx-proxy-manage
    image: jc21/nginx-proxy-manager:latest
    dns:
      - 192.168.100.2
    environment:
      - DISABLE_IPV6=true
    volumes:
      - /services/data/nginx-proxy-manager:/data:rw
      - /services/config/letsencrypt:/etc/letsencrypt:rw
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.6
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - cloudflare-ddns
      - unbound

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    dns:
      - 192.168.100.2
    volumes:
      - /services/config/homepage:/app/config:rw
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.7
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    dns:
      - 192.168.100.2
    volumes:
      - /services/data/portainer:/data
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  semaphore-ui:
    container_name: semaphore-ui
    image: semaphoreui/semaphore:latest
    dns:
      - 192.168.100.2
    environment:
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN_NAME={SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_EMAIL={SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN={SEMAPHORE_ADMIN}
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.11
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: timothyjmiller/cloudflare-ddns:latest
    dns:
      - 192.168.100.2
    security_opt:
      - no-new-privileges:true
    networks:
      homelab-internal:
        ipv4_address: 192.168.100.12
    restart: unless-stopped
    volumes:
      - /services/config/cloudflare-ddns/config.json:/config.json:rw

########## External ##########
  traefik:
    container_name: traefik
    image: traefik:v2.9
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS=:443
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_HTTPCHALLENGE_ENTRYPOINT=http
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL=${TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL}
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_STORAGE=/letsencrypt/acme.json
      - `RAEFIK_CERTIFICATESRESOLVERS_LE_ACME_HTTPCHALLENGE=true
      - TRAEFIK_API=true
    volumes:
      - /services/data/traefik:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /services/config/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    volumes:
      - /services/config/nextcloud:/var/www/html/config
      - /services/data/nextcloud/data:/var/www/html/data
      - /services/data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /services/data/nextcloud/apps:/var/www/html/apps
      - /services/data/nextcloud/themes:/var/www/html/themes
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - TRUSTED_PROXIES=traefik
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=127.0.0.1
      - REDIS_HOST=127.0.0.1
      - SKIP_DOMAIN_VALIDATION=true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    network_mode: service:nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /services/data/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    network_mode: service:nextcloud
    volumes:
      - /services/data/nextcloud-redis:/data
    depends_on:
      - cloudflare-ddns

networks:
  homelab-internal:
    ipam:
      config:
        - subnet: 192.168.100.0/24