services:
  traefik:
    image: traefik:2.9
    container_name: traefik
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /services/data/traefik:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - homelab-external
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 1m
      timeout: 10s
      retries: 3

  nextcloud:
    container_name: nextcloud
    image: nextcloud:apache
    volumes:
      - /services/config/nextcloud:/var/www/html/config
      - /services/data/nextcloud/data:/var/www/html/data
      - /services/data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /services/data/nextcloud/apps:/var/www/html/apps
      - /services/data/nextcloud/themes:/var/www/html/themes
      - /services/data/geoipupdate:/geoipupdate
      - /mnt/external-drive:/mnt/external-drive:ro
    environment:
      - OVERWRITEHOST=${OVERWRITEHOST}
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - TRUSTED_PROXIES=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      - APACHE_DISABLE_REWRITE_IP=1
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=localhost
      - REDIS_HOST=localhost
      - SKIL_DOMAIN_VALIDATION=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextcloud.loadbalancer.passhostheader=true"
      - "traefik.docker.network=homelab-external"
    restart: unless-stopped
    networks:
      - homelab-external
    depends_on:
      - cloudflare-ddns
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 1m
      timeout: 10s
      retries: 3

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    network_mode: service:nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /services/data/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1m
      timeout: 10s
      retries: 3

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    network_mode: service:nextcloud
    volumes:
      - /services/data/nextcloud-redis:/data
    depends_on:
      - cloudflare-ddns
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 10s
      retries: 3

  geoipupdate:
    image: maxmindinc/geoipupdate:latest
    container_name: geoipupdate
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIPUPDATE_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIPUPDATE_LICENSE_KEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - /services/data/geoipupdate:/usr/share/GeoIP
    healthcheck:
      test: ["CMD", "geoipupdate", "-v"]
      interval: 1h
      timeout: 60s
      retries: 3

networks:
  homelab-external:
