services:
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    environment:
      - UNBOUND_IPV4_ADDRESS=192.168.100.2
    volumes:
      - /services/config/unbound:/opt/unbound/etc/unbound:rw
    networks:
      homelab:
        ipv4_address: 192.168.100.2
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns

  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:v1.0.20210914-ls7
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - /services/config/wireguard:/config:rw
      - /services/config/wireguard-ui/wg0.conf:/config/wg0.conf:rw
    dns:
      - 192.168.100.2
    networks:
      homelab:
        ipv4_address: 192.168.100.3
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns
      - unbound

  wireguard-ui:
    container_name: wireguard-ui
    image: ngoduykhanh/wireguard-ui:latest
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - WGUI_USERNAME=${WGUI_USERNAME}
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /services/data/wireguard-ui:/app/db:rw
      - /services/config/wireguard-ui:/config:rw
    depends_on:
      - wireguard
      - cloudflare-ddns
      - unbound

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - DNS1=192.168.100.2
      - DNS2=192.168.100.2
      - PIHOLE_IPV4_ADDRESS=192.168.100.3
      - WEBPASSWORD=${WEBPASSWORD}
    dns:
      - 192.168.100.2
    networks:
      homelab:
        ipv4_address: 192.168.100.4
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  # hello:
  #   container_name: hello
  #   image: nginxdemos/hello:latest
  #   dns:
  #     - 192.168.100.2
  #   networks:
  #     homelab:
  #       ipv4_address: 192.168.100.5
  #   restart: unless-stopped
  #   depends_on:
  #     - wireguard
  #     - wireguard-ui
  #     - cloudflare-ddns
  #     - unbound

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    dns:
      - 192.168.100.2
    environment:
      - DISABLE_IPV6=true
    volumes:
      - /services/data/nginx-proxy-manager:/data:rw
      - /services/config/letsencrypt:/etc/letsencrypt:rw
    networks:
      homelab:
        ipv4_address: 192.168.100.6
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - cloudflare-ddns
      - unbound

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    dns:
      - 192.168.100.2
    volumes:
      - /services/config/homepage:/app/config:rw
    networks:
      homelab:
        ipv4_address: 192.168.100.7
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    dns:
      - 192.168.100.2
    volumes:
      - /services/data/portainer:/data
    networks:
      homelab:
        ipv4_address: 192.168.100.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    dns:
      - 192.168.100.2
    volumes:
      - /services/config/nextcloud:/var/www/html/config
      - /services/data/nextcloud/data:/var/www/html/data
      - /services/data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /services/data/nextcloud/apps:/var/www/html/apps
      - /services/data/nextcloud/themes:/var/www/html/themes
    networks:
      homelab:
        ipv4_address: 192.168.100.9
    environment:
      - NEXTCLOUD_DB_TYPE=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=127.0.0.1
      - REDIS_HOST=127.0.0.1
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - cloudflare-ddns
      - unbound


  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    network_mode: service:nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /services/data/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - cloudflare-ddns
      - unbound

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    network_mode: service:nextcloud
    volumes:
      - /services/data/nextcloud-redis:/data

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    dns:
      - 192.168.100.2
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${DOMAIN}
    volumes:
      - /services/data/vaultwarden:/data:rw
    networks:
      homelab:
        ipv4_address: 192.168.100.10
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  semaphore-ui:
    container_name: semaphore-ui
    image: semaphoreui/semaphore:latest
    dns:
      - 192.168.100.2
    environment:
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN_NAME={SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_EMAIL={SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN={SEMAPHORE_ADMIN}
    networks:
      homelab:
        ipv4_address: 192.168.100.11
    restart: unless-stopped
    depends_on:
      - wireguard
      - wireguard-ui
      - nginx-proxy-manager
      - cloudflare-ddns
      - unbound

  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: timothyjmiller/cloudflare-ddns:latest
    dns:
      - 192.168.100.2
    security_opt:
      - no-new-privileges:true
    networks:
      homelab:
        ipv4_address: 192.168.100.12
    restart: unless-stopped
    volumes:
      - /services/config/cloudflare-ddns/config.json:/config.json:rw

networks:
  homelab:
    ipam:
      config:
        - subnet: 192.168.100.0/24
