services:
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:v1.0.20210914-ls7
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - /services/config/wireguard:/config:rw
      - /services/config/wireguard-ui/wg0.conf:/config/wg0.conf:rw
    dns:
      - 192.168.100.2
    networks:
      homelab:
        ipv4_address: 192.168.100.3
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    restart: unless-stopped
    depends_on:
      - cloudflare-ddns
      - unbound

  wireguard-ui:
    container_name: wireguard-ui
    image: ngoduykhanh/wireguard-ui:latest
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - WGUI_USERNAME=${WGUI_USERNAME}
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /services/data/wireguard-ui:/app/db:rw
      - /services/config/wireguard-ui:/config:rw
    depends_on:
      - wireguard
      - cloudflare-ddns
      - unbound

networks:
  homelab:
    external: true
