services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    dns:
      - 192.168.100.2
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${DOMAIN}
    volumes:
      - /services/data/vaultwarden:/data:rw
    networks:
      homelab:
        ipv4_address
